const data = {
    "location": {
        "name": "Viamao",
        "region": "Rio Grande do Sul",
        "country": "Brazil",
        "lat": -30.1,
        "lon": -50.85,
        "tz_id": "America/Sao_Paulo",
        "localtime_epoch": 1697837377,
        "localtime": "2023-10-20 18:29"
    },
    "current": {
        "last_updated_epoch": 1697836500,
        "last_updated": "2023-10-20 18:15",
        "temp_c": 21,
        "temp_f": 69.8,
        "is_day": 1,
        "condition": {
            "text": "Partly cloudy",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003
        },
        "wind_mph": 18.6,
        "wind_kph": 29.9,
        "wind_degree": 100,
        "wind_dir": "E",
        "pressure_mb": 1017,
        "pressure_in": 30.03,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 73,
        "cloud": 50,
        "feelslike_c": 21,
        "feelslike_f": 69.8,
        "vis_km": 10,
        "vis_miles": 6,
        "uv": 5,
        "gust_mph": 15.1,
        "gust_kph": 24.4
    }
}
{
    "location": {
      "name": "London",
      "region": "City of London, Greater London",
      "country": "United Kingdom",
      "lat": 51.52,
      "lon": -0.11,
      "tz_id": "Europe/London",
      "localtime_epoch": 1698416309,
      "localtime": "2023-10-27 15:18"
    },
    "current": {
      "last_updated_epoch": 1698416100,
      "last_updated": "2023-10-27 15:15",
      "temp_c": 14,
      "temp_f": 57.2,
      "is_day": 1,
      "condition": {
        "text": "Partly cloudy",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
        "code": 1003
      },
      "wind_mph": 12.5,
      "wind_kph": 20.2,
      "wind_degree": 220,
      "wind_dir": "SW",
      "pressure_mb": 990,
      "pressure_in": 29.23,
      "precip_mm": 0,
      "precip_in": 0,
      "humidity": 67,
      "cloud": 50,
      "feelslike_c": 13.1,
      "feelslike_f": 55.6,
      "vis_km": 10,
      "vis_miles": 6,
      "uv": 4,
      "gust_mph": 10.8,
      "gust_kph": 17.4
    },
    "forecast": {
      "forecastday": [
        {
          "date": "2023-10-27",
          "date_epoch": 1698364800,
          "day": {
            "maxtemp_c": 13.8,
            "maxtemp_f": 56.9,
            "mintemp_c": 9.9,
            "mintemp_f": 49.8,
            "avgtemp_c": 11.2,
            "avgtemp_f": 52.1,
            "maxwind_mph": 8.9,
            "maxwind_kph": 14.4,
            "totalprecip_mm": 5.66,
            "totalprecip_in": 0.22,
            "totalsnow_cm": 0,
            "avgvis_km": 9.6,
            "avgvis_miles": 5,
            "avghumidity": 86,
            "daily_will_it_rain": 1,
            "daily_chance_of_rain": 94,
            "daily_will_it_snow": 0,
            "daily_chance_of_snow": 0,
            "condition": {
              "text": "Moderate rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
              "code": 1189
            },
            "uv": 3
          },
          "astro": {
            "sunrise": "07:45 AM",
            "sunset": "05:44 PM",
            "moonrise": "05:13 PM",
            "moonset": "05:39 AM",
            "moon_phase": "Waxing Gibbous",
            "moon_illumination": 95,
            "is_moon_up": 1,
            "is_sun_up": 0
          },
          "hour": [
            {
              "time_epoch": 1698361200,
              "time": "2023-10-27 00:00",
              "temp_c": 10.2,
              "temp_f": 50.4,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 3.4,
              "wind_kph": 5.4,
              "wind_degree": 242,
              "wind_dir": "WSW",
              "pressure_mb": 990,
              "pressure_in": 29.23,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 93,
              "cloud": 21,
              "feelslike_c": 9.9,
              "feelslike_f": 49.9,
              "windchill_c": 9.9,
              "windchill_f": 49.9,
              "heatindex_c": 10.3,
              "heatindex_f": 50.5,
              "dewpoint_c": 9.2,
              "dewpoint_f": 48.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 5.9,
              "gust_kph": 9.5,
              "uv": 1
            },
            {
              "time_epoch": 1698364800,
              "time": "2023-10-27 01:00",
              "temp_c": 10.1,
              "temp_f": 50.2,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 3.1,
              "wind_kph": 5,
              "wind_degree": 222,
              "wind_dir": "SW",
              "pressure_mb": 990,
              "pressure_in": 29.23,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 93,
              "cloud": 25,
              "feelslike_c": 9.9,
              "feelslike_f": 49.8,
              "windchill_c": 9.9,
              "windchill_f": 49.8,
              "heatindex_c": 10.1,
              "heatindex_f": 50.2,
              "dewpoint_c": 9.1,
              "dewpoint_f": 48.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 5.5,
              "gust_kph": 8.9,
              "uv": 1
            },
            {
              "time_epoch": 1698368400,
              "time": "2023-10-27 02:00",
              "temp_c": 10,
              "temp_f": 50,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 2.5,
              "wind_kph": 4,
              "wind_degree": 215,
              "wind_dir": "SW",
              "pressure_mb": 990,
              "pressure_in": 29.23,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 93,
              "cloud": 60,
              "feelslike_c": 10.1,
              "feelslike_f": 50.3,
              "windchill_c": 10.1,
              "windchill_f": 50.3,
              "heatindex_c": 10,
              "heatindex_f": 50.1,
              "dewpoint_c": 8.9,
              "dewpoint_f": 48,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 4.4,
              "gust_kph": 7.1,
              "uv": 1
            },
            {
              "time_epoch": 1698372000,
              "time": "2023-10-27 03:00",
              "temp_c": 10.1,
              "temp_f": 50.1,
              "is_day": 0,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                "code": 1063
              },
              "wind_mph": 3.1,
              "wind_kph": 5,
              "wind_degree": 207,
              "wind_dir": "SSW",
              "pressure_mb": 989,
              "pressure_in": 29.22,
              "precip_mm": 0.02,
              "precip_in": 0,
              "humidity": 92,
              "cloud": 74,
              "feelslike_c": 9.8,
              "feelslike_f": 49.7,
              "windchill_c": 9.8,
              "windchill_f": 49.7,
              "heatindex_c": 10.1,
              "heatindex_f": 50.1,
              "dewpoint_c": 8.9,
              "dewpoint_f": 48,
              "will_it_rain": 1,
              "chance_of_rain": 71,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 5.6,
              "gust_kph": 9.1,
              "uv": 1
            },
            {
              "time_epoch": 1698375600,
              "time": "2023-10-27 04:00",
              "temp_c": 10,
              "temp_f": 50,
              "is_day": 0,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                "code": 1063
              },
              "wind_mph": 2.5,
              "wind_kph": 4,
              "wind_degree": 202,
              "wind_dir": "SSW",
              "pressure_mb": 989,
              "pressure_in": 29.22,
              "precip_mm": 0.05,
              "precip_in": 0,
              "humidity": 92,
              "cloud": 76,
              "feelslike_c": 10.1,
              "feelslike_f": 50.1,
              "windchill_c": 10.1,
              "windchill_f": 50.1,
              "heatindex_c": 10,
              "heatindex_f": 50,
              "dewpoint_c": 8.8,
              "dewpoint_f": 47.8,
              "will_it_rain": 1,
              "chance_of_rain": 83,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 4.4,
              "gust_kph": 7.1,
              "uv": 1
            },
            {
              "time_epoch": 1698379200,
              "time": "2023-10-27 05:00",
              "temp_c": 9.9,
              "temp_f": 49.8,
              "is_day": 0,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                "code": 1240
              },
              "wind_mph": 2.9,
              "wind_kph": 4.7,
              "wind_degree": 198,
              "wind_dir": "SSW",
              "pressure_mb": 990,
              "pressure_in": 29.22,
              "precip_mm": 0.48,
              "precip_in": 0.02,
              "humidity": 93,
              "cloud": 65,
              "feelslike_c": 9.7,
              "feelslike_f": 49.5,
              "windchill_c": 9.7,
              "windchill_f": 49.5,
              "heatindex_c": 9.9,
              "heatindex_f": 49.7,
              "dewpoint_c": 8.8,
              "dewpoint_f": 47.9,
              "will_it_rain": 1,
              "chance_of_rain": 73,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 5.1,
              "gust_kph": 8.2,
              "uv": 1
            },
            {
              "time_epoch": 1698382800,
              "time": "2023-10-27 06:00",
              "temp_c": 10,
              "temp_f": 50,
              "is_day": 0,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                "code": 1240
              },
              "wind_mph": 2.7,
              "wind_kph": 4.3,
              "wind_degree": 214,
              "wind_dir": "SW",
              "pressure_mb": 989,
              "pressure_in": 29.22,
              "precip_mm": 0.83,
              "precip_in": 0.03,
              "humidity": 94,
              "cloud": 100,
              "feelslike_c": 10,
              "feelslike_f": 50,
              "windchill_c": 10,
              "windchill_f": 50,
              "heatindex_c": 10,
              "heatindex_f": 50,
              "dewpoint_c": 9.1,
              "dewpoint_f": 48.4,
              "will_it_rain": 1,
              "chance_of_rain": 75,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 4.5,
              "gust_kph": 7.2,
              "uv": 1
            },
            {
              "time_epoch": 1698386400,
              "time": "2023-10-27 07:00",
              "temp_c": 10.1,
              "temp_f": 50.1,
              "is_day": 0,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                "code": 1240
              },
              "wind_mph": 2.9,
              "wind_kph": 4.7,
              "wind_degree": 222,
              "wind_dir": "SW",
              "pressure_mb": 989,
              "pressure_in": 29.22,
              "precip_mm": 1.19,
              "precip_in": 0.05,
              "humidity": 96,
              "cloud": 100,
              "feelslike_c": 9.9,
              "feelslike_f": 49.8,
              "windchill_c": 9.9,
              "windchill_f": 49.8,
              "heatindex_c": 10.1,
              "heatindex_f": 50.1,
              "dewpoint_c": 9.4,
              "dewpoint_f": 49,
              "will_it_rain": 0,
              "chance_of_rain": 59,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 4.6,
              "gust_kph": 7.4,
              "uv": 1
            },
            {
              "time_epoch": 1698390000,
              "time": "2023-10-27 08:00",
              "temp_c": 10.4,
              "temp_f": 50.6,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 2.2,
              "wind_kph": 3.6,
              "wind_degree": 193,
              "wind_dir": "SSW",
              "pressure_mb": 990,
              "pressure_in": 29.23,
              "precip_mm": 0.24,
              "precip_in": 0.01,
              "humidity": 95,
              "cloud": 100,
              "feelslike_c": 10.6,
              "feelslike_f": 51.2,
              "windchill_c": 10.6,
              "windchill_f": 51.2,
              "heatindex_c": 10.4,
              "heatindex_f": 50.6,
              "dewpoint_c": 9.6,
              "dewpoint_f": 49.3,
              "will_it_rain": 0,
              "chance_of_rain": 64,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.4,
              "gust_kph": 5.5,
              "uv": 3
            },
            {
              "time_epoch": 1698393600,
              "time": "2023-10-27 09:00",
              "temp_c": 11.1,
              "temp_f": 51.9,
              "is_day": 1,
              "condition": {
                "text": "Thundery outbreaks possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/200.png",
                "code": 1087
              },
              "wind_mph": 2.5,
              "wind_kph": 4,
              "wind_degree": 201,
              "wind_dir": "SSW",
              "pressure_mb": 990,
              "pressure_in": 29.23,
              "precip_mm": 0.05,
              "precip_in": 0,
              "humidity": 92,
              "cloud": 72,
              "feelslike_c": 11.3,
              "feelslike_f": 52.4,
              "windchill_c": 11.3,
              "windchill_f": 52.4,
              "heatindex_c": 11.1,
              "heatindex_f": 51.9,
              "dewpoint_c": 9.8,
              "dewpoint_f": 49.6,
              "will_it_rain": 1,
              "chance_of_rain": 73,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 3.6,
              "gust_kph": 5.8,
              "uv": 3
            },
            {
              "time_epoch": 1698397200,
              "time": "2023-10-27 10:00",
              "temp_c": 12,
              "temp_f": 53.6,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 5.1,
              "wind_kph": 8.3,
              "wind_degree": 234,
              "wind_dir": "SW",
              "pressure_mb": 990,
              "pressure_in": 29.23,
              "precip_mm": 0.43,
              "precip_in": 0.02,
              "humidity": 86,
              "cloud": 99,
              "feelslike_c": 11.3,
              "feelslike_f": 52.3,
              "windchill_c": 11.3,
              "windchill_f": 52.3,
              "heatindex_c": 12,
              "heatindex_f": 53.6,
              "dewpoint_c": 9.7,
              "dewpoint_f": 49.4,
              "will_it_rain": 1,
              "chance_of_rain": 94,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 7.7,
              "gust_kph": 12.4,
              "uv": 3
            },
            {
              "time_epoch": 1698400800,
              "time": "2023-10-27 11:00",
              "temp_c": 11.9,
              "temp_f": 53.5,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 3.6,
              "wind_kph": 5.8,
              "wind_degree": 231,
              "wind_dir": "SW",
              "pressure_mb": 990,
              "pressure_in": 29.23,
              "precip_mm": 0.11,
              "precip_in": 0,
              "humidity": 86,
              "cloud": 100,
              "feelslike_c": 11.8,
              "feelslike_f": 53.2,
              "windchill_c": 11.8,
              "windchill_f": 53.2,
              "heatindex_c": 12,
              "heatindex_f": 53.5,
              "dewpoint_c": 9.6,
              "dewpoint_f": 49.4,
              "will_it_rain": 0,
              "chance_of_rain": 59,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 5.5,
              "gust_kph": 8.8,
              "uv": 3
            },
            {
              "time_epoch": 1698404400,
              "time": "2023-10-27 12:00",
              "temp_c": 12.2,
              "temp_f": 54,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 5.8,
              "wind_kph": 9.4,
              "wind_degree": 225,
              "wind_dir": "SW",
              "pressure_mb": 990,
              "pressure_in": 29.24,
              "precip_mm": 0.38,
              "precip_in": 0.02,
              "humidity": 84,
              "cloud": 100,
              "feelslike_c": 11.4,
              "feelslike_f": 52.5,
              "windchill_c": 11.4,
              "windchill_f": 52.5,
              "heatindex_c": 12.2,
              "heatindex_f": 54,
              "dewpoint_c": 9.5,
              "dewpoint_f": 49.2,
              "will_it_rain": 0,
              "chance_of_rain": 70,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 9.2,
              "gust_kph": 14.8,
              "uv": 3
            },
            {
              "time_epoch": 1698408000,
              "time": "2023-10-27 13:00",
              "temp_c": 13,
              "temp_f": 55.4,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 6,
              "wind_kph": 9.7,
              "wind_degree": 221,
              "wind_dir": "SW",
              "pressure_mb": 990,
              "pressure_in": 29.24,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 77,
              "cloud": 25,
              "feelslike_c": 12.3,
              "feelslike_f": 54.1,
              "windchill_c": 12.3,
              "windchill_f": 54.1,
              "heatindex_c": 13,
              "heatindex_f": 55.4,
              "dewpoint_c": 9.1,
              "dewpoint_f": 48.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 8.3,
              "gust_kph": 13.4,
              "uv": 4
            },
            {
              "time_epoch": 1698411600,
              "time": "2023-10-27 14:00",
              "temp_c": 13.8,
              "temp_f": 56.9,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 6.9,
              "wind_kph": 11.2,
              "wind_degree": 215,
              "wind_dir": "SW",
              "pressure_mb": 990,
              "pressure_in": 29.23,
              "precip_mm": 0.02,
              "precip_in": 0,
              "humidity": 73,
              "cloud": 72,
              "feelslike_c": 13.1,
              "feelslike_f": 55.5,
              "windchill_c": 13.1,
              "windchill_f": 55.5,
              "heatindex_c": 13.8,
              "heatindex_f": 56.9,
              "dewpoint_c": 9.1,
              "dewpoint_f": 48.4,
              "will_it_rain": 0,
              "chance_of_rain": 70,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 9.3,
              "gust_kph": 14.9,
              "uv": 3
            },
            {
              "time_epoch": 1698415200,
              "time": "2023-10-27 15:00",
              "temp_c": 14,
              "temp_f": 57.2,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 12.5,
              "wind_kph": 20.2,
              "wind_degree": 220,
              "wind_dir": "SW",
              "pressure_mb": 990,
              "pressure_in": 29.23,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 67,
              "cloud": 50,
              "feelslike_c": 12.7,
              "feelslike_f": 54.9,
              "windchill_c": 12.7,
              "windchill_f": 54.9,
              "heatindex_c": 13.7,
              "heatindex_f": 56.7,
              "dewpoint_c": 9.1,
              "dewpoint_f": 48.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 10.8,
              "gust_kph": 17.4,
              "uv": 4
            },
            {
              "time_epoch": 1698418800,
              "time": "2023-10-27 16:00",
              "temp_c": 12.6,
              "temp_f": 54.8,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 8.7,
              "wind_kph": 14,
              "wind_degree": 206,
              "wind_dir": "SSW",
              "pressure_mb": 990,
              "pressure_in": 29.23,
              "precip_mm": 1.22,
              "precip_in": 0.05,
              "humidity": 78,
              "cloud": 79,
              "feelslike_c": 11.3,
              "feelslike_f": 52.3,
              "windchill_c": 11.3,
              "windchill_f": 52.3,
              "heatindex_c": 12.7,
              "heatindex_f": 54.8,
              "dewpoint_c": 8.9,
              "dewpoint_f": 48,
              "will_it_rain": 1,
              "chance_of_rain": 90,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 13.4,
              "gust_kph": 21.6,
              "uv": 3
            },
            {
              "time_epoch": 1698422400,
              "time": "2023-10-27 17:00",
              "temp_c": 11.9,
              "temp_f": 53.5,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 8.7,
              "wind_kph": 14,
              "wind_degree": 216,
              "wind_dir": "SW",
              "pressure_mb": 990,
              "pressure_in": 29.24,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 80,
              "cloud": 27,
              "feelslike_c": 10.4,
              "feelslike_f": 50.7,
              "windchill_c": 10.4,
              "windchill_f": 50.7,
              "heatindex_c": 11.9,
              "heatindex_f": 53.5,
              "dewpoint_c": 8.5,
              "dewpoint_f": 47.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 13.8,
              "gust_kph": 22.3,
              "uv": 4
            },
            {
              "time_epoch": 1698426000,
              "time": "2023-10-27 18:00",
              "temp_c": 11.5,
              "temp_f": 52.7,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 7.8,
              "wind_kph": 12.6,
              "wind_degree": 215,
              "wind_dir": "SW",
              "pressure_mb": 991,
              "pressure_in": 29.25,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 81,
              "cloud": 25,
              "feelslike_c": 10,
              "feelslike_f": 50.1,
              "windchill_c": 10,
              "windchill_f": 50.1,
              "heatindex_c": 11.5,
              "heatindex_f": 52.7,
              "dewpoint_c": 8.4,
              "dewpoint_f": 47.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 12.9,
              "gust_kph": 20.7,
              "uv": 1
            },
            {
              "time_epoch": 1698429600,
              "time": "2023-10-27 19:00",
              "temp_c": 10.9,
              "temp_f": 51.7,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 6,
              "wind_kph": 9.7,
              "wind_degree": 199,
              "wind_dir": "SSW",
              "pressure_mb": 991,
              "pressure_in": 29.26,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 84,
              "cloud": 42,
              "feelslike_c": 9.8,
              "feelslike_f": 49.6,
              "windchill_c": 9.8,
              "windchill_f": 49.6,
              "heatindex_c": 10.9,
              "heatindex_f": 51.7,
              "dewpoint_c": 8.3,
              "dewpoint_f": 46.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 10.3,
              "gust_kph": 16.6,
              "uv": 1
            },
            {
              "time_epoch": 1698433200,
              "time": "2023-10-27 20:00",
              "temp_c": 10.5,
              "temp_f": 50.8,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 4.9,
              "wind_kph": 7.9,
              "wind_degree": 179,
              "wind_dir": "S",
              "pressure_mb": 991,
              "pressure_in": 29.25,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 85,
              "cloud": 15,
              "feelslike_c": 9.6,
              "feelslike_f": 49.2,
              "windchill_c": 9.6,
              "windchill_f": 49.2,
              "heatindex_c": 10.5,
              "heatindex_f": 50.8,
              "dewpoint_c": 8.1,
              "dewpoint_f": 46.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 9,
              "gust_kph": 14.5,
              "uv": 1
            },
            {
              "time_epoch": 1698436800,
              "time": "2023-10-27 21:00",
              "temp_c": 10.4,
              "temp_f": 50.7,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 5.8,
              "wind_kph": 9.4,
              "wind_degree": 170,
              "wind_dir": "S",
              "pressure_mb": 991,
              "pressure_in": 29.25,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 84,
              "cloud": 33,
              "feelslike_c": 9.2,
              "feelslike_f": 48.6,
              "windchill_c": 9.2,
              "windchill_f": 48.6,
              "heatindex_c": 10.4,
              "heatindex_f": 50.7,
              "dewpoint_c": 7.8,
              "dewpoint_f": 46,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 10.6,
              "gust_kph": 17,
              "uv": 1
            },
            {
              "time_epoch": 1698440400,
              "time": "2023-10-27 22:00",
              "temp_c": 10.6,
              "temp_f": 51.1,
              "is_day": 0,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                "code": 1063
              },
              "wind_mph": 7.4,
              "wind_kph": 11.9,
              "wind_degree": 171,
              "wind_dir": "S",
              "pressure_mb": 990,
              "pressure_in": 29.25,
              "precip_mm": 0.02,
              "precip_in": 0,
              "humidity": 83,
              "cloud": 100,
              "feelslike_c": 9.1,
              "feelslike_f": 48.3,
              "windchill_c": 9.1,
              "windchill_f": 48.3,
              "heatindex_c": 10.6,
              "heatindex_f": 51.1,
              "dewpoint_c": 7.9,
              "dewpoint_f": 46.2,
              "will_it_rain": 1,
              "chance_of_rain": 76,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 12.4,
              "gust_kph": 19.9,
              "uv": 1
            },
            {
              "time_epoch": 1698444000,
              "time": "2023-10-27 23:00",
              "temp_c": 10.8,
              "temp_f": 51.5,
              "is_day": 0,
              "condition": {
                "text": "Light drizzle",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                "code": 1153
              },
              "wind_mph": 8.9,
              "wind_kph": 14.4,
              "wind_degree": 175,
              "wind_dir": "S",
              "pressure_mb": 990,
              "pressure_in": 29.23,
              "precip_mm": 0.6,
              "precip_in": 0.02,
              "humidity": 86,
              "cloud": 100,
              "feelslike_c": 9,
              "feelslike_f": 48.2,
              "windchill_c": 9,
              "windchill_f": 48.2,
              "heatindex_c": 10.8,
              "heatindex_f": 51.5,
              "dewpoint_c": 8.6,
              "dewpoint_f": 47.5,
              "will_it_rain": 0,
              "chance_of_rain": 57,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 13.7,
              "gust_kph": 22,
              "uv": 1
            }
          ]
        },
        {
          "date": "2023-10-28",
          "date_epoch": 1698451200,
          "day": {
            "maxtemp_c": 14.6,
            "maxtemp_f": 58.3,
            "mintemp_c": 10.4,
            "mintemp_f": 50.7,
            "avgtemp_c": 12.4,
            "avgtemp_f": 54.4,
            "maxwind_mph": 18.8,
            "maxwind_kph": 30.2,
            "totalprecip_mm": 12.35,
            "totalprecip_in": 0.49,
            "totalsnow_cm": 0,
            "avgvis_km": 9.3,
            "avgvis_miles": 5,
            "avghumidity": 82,
            "daily_will_it_rain": 1,
            "daily_chance_of_rain": 88,
            "daily_will_it_snow": 0,
            "daily_chance_of_snow": 0,
            "condition": {
              "text": "Moderate rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
              "code": 1189
            },
            "uv": 3
          },
          "astro": {
            "sunrise": "07:47 AM",
            "sunset": "05:42 PM",
            "moonrise": "05:28 PM",
            "moonset": "07:06 AM",
            "moon_phase": "Full Moon",
            "moon_illumination": 99,
            "is_moon_up": 1,
            "is_sun_up": 0
          },
          "hour": [
            {
              "time_epoch": 1698447600,
              "time": "2023-10-28 00:00",
              "temp_c": 10.4,
              "temp_f": 50.7,
              "is_day": 0,
              "condition": {
                "text": "Moderate rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/302.png",
                "code": 1189
              },
              "wind_mph": 7.8,
              "wind_kph": 12.6,
              "wind_degree": 182,
              "wind_dir": "S",
              "pressure_mb": 989,
              "pressure_in": 29.21,
              "precip_mm": 3.88,
              "precip_in": 0.15,
              "humidity": 92,
              "cloud": 100,
              "feelslike_c": 8.7,
              "feelslike_f": 47.6,
              "windchill_c": 8.7,
              "windchill_f": 47.6,
              "heatindex_c": 10.4,
              "heatindex_f": 50.7,
              "dewpoint_c": 9.1,
              "dewpoint_f": 48.5,
              "will_it_rain": 0,
              "chance_of_rain": 65,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 7,
              "vis_miles": 4,
              "gust_mph": 11.6,
              "gust_kph": 18.7,
              "uv": 1
            },
            {
              "time_epoch": 1698451200,
              "time": "2023-10-28 01:00",
              "temp_c": 10.4,
              "temp_f": 50.7,
              "is_day": 0,
              "condition": {
                "text": "Light rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
                "code": 1183
              },
              "wind_mph": 4.9,
              "wind_kph": 7.9,
              "wind_degree": 165,
              "wind_dir": "SSE",
              "pressure_mb": 989,
              "pressure_in": 29.21,
              "precip_mm": 2.13,
              "precip_in": 0.08,
              "humidity": 95,
              "cloud": 100,
              "feelslike_c": 9.5,
              "feelslike_f": 49.1,
              "windchill_c": 9.5,
              "windchill_f": 49.1,
              "heatindex_c": 10.4,
              "heatindex_f": 50.7,
              "dewpoint_c": 9.7,
              "dewpoint_f": 49.4,
              "will_it_rain": 0,
              "chance_of_rain": 60,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 7.4,
              "gust_kph": 12,
              "uv": 1
            },
            {
              "time_epoch": 1698454800,
              "time": "2023-10-28 02:00",
              "temp_c": 10.9,
              "temp_f": 51.6,
              "is_day": 0,
              "condition": {
                "text": "Moderate or heavy rain with thunder",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/389.png",
                "code": 1276
              },
              "wind_mph": 6,
              "wind_kph": 9.7,
              "wind_degree": 196,
              "wind_dir": "SSW",
              "pressure_mb": 989,
              "pressure_in": 29.2,
              "precip_mm": 1.04,
              "precip_in": 0.04,
              "humidity": 94,
              "cloud": 100,
              "feelslike_c": 9.7,
              "feelslike_f": 49.5,
              "windchill_c": 9.7,
              "windchill_f": 49.5,
              "heatindex_c": 10.9,
              "heatindex_f": 51.5,
              "dewpoint_c": 10,
              "dewpoint_f": 49.9,
              "will_it_rain": 0,
              "chance_of_rain": 61,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 6,
              "vis_miles": 3,
              "gust_mph": 9.3,
              "gust_kph": 15,
              "uv": 1
            },
            {
              "time_epoch": 1698458400,
              "time": "2023-10-28 03:00",
              "temp_c": 11.3,
              "temp_f": 52.4,
              "is_day": 0,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                "code": 1240
              },
              "wind_mph": 7.6,
              "wind_kph": 12.2,
              "wind_degree": 225,
              "wind_dir": "SW",
              "pressure_mb": 989,
              "pressure_in": 29.19,
              "precip_mm": 0.56,
              "precip_in": 0.02,
              "humidity": 90,
              "cloud": 70,
              "feelslike_c": 9.9,
              "feelslike_f": 49.8,
              "windchill_c": 9.9,
              "windchill_f": 49.8,
              "heatindex_c": 11.3,
              "heatindex_f": 52.4,
              "dewpoint_c": 9.8,
              "dewpoint_f": 49.7,
              "will_it_rain": 1,
              "chance_of_rain": 84,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 12,
              "gust_kph": 19.3,
              "uv": 1
            },
            {
              "time_epoch": 1698462000,
              "time": "2023-10-28 04:00",
              "temp_c": 11.4,
              "temp_f": 52.6,
              "is_day": 0,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                "code": 1240
              },
              "wind_mph": 9.8,
              "wind_kph": 15.8,
              "wind_degree": 224,
              "wind_dir": "SW",
              "pressure_mb": 989,
              "pressure_in": 29.2,
              "precip_mm": 0.43,
              "precip_in": 0.02,
              "humidity": 87,
              "cloud": 81,
              "feelslike_c": 9.6,
              "feelslike_f": 49.3,
              "windchill_c": 9.6,
              "windchill_f": 49.3,
              "heatindex_c": 11.4,
              "heatindex_f": 52.6,
              "dewpoint_c": 9.3,
              "dewpoint_f": 48.8,
              "will_it_rain": 0,
              "chance_of_rain": 65,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 15.7,
              "gust_kph": 25.3,
              "uv": 1
            },
            {
              "time_epoch": 1698465600,
              "time": "2023-10-28 05:00",
              "temp_c": 11.1,
              "temp_f": 52.1,
              "is_day": 0,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                "code": 1063
              },
              "wind_mph": 9.8,
              "wind_kph": 15.8,
              "wind_degree": 229,
              "wind_dir": "SW",
              "pressure_mb": 989,
              "pressure_in": 29.21,
              "precip_mm": 0.06,
              "precip_in": 0,
              "humidity": 87,
              "cloud": 91,
              "feelslike_c": 9.2,
              "feelslike_f": 48.6,
              "windchill_c": 9.2,
              "windchill_f": 48.6,
              "heatindex_c": 11.2,
              "heatindex_f": 52.1,
              "dewpoint_c": 9,
              "dewpoint_f": 48.2,
              "will_it_rain": 0,
              "chance_of_rain": 64,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 15.7,
              "gust_kph": 25.3,
              "uv": 1
            },
            {
              "time_epoch": 1698469200,
              "time": "2023-10-28 06:00",
              "temp_c": 10.8,
              "temp_f": 51.5,
              "is_day": 0,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                "code": 1063
              },
              "wind_mph": 9.8,
              "wind_kph": 15.8,
              "wind_degree": 231,
              "wind_dir": "SW",
              "pressure_mb": 990,
              "pressure_in": 29.24,
              "precip_mm": 0.13,
              "precip_in": 0.01,
              "humidity": 88,
              "cloud": 53,
              "feelslike_c": 8.9,
              "feelslike_f": 47.9,
              "windchill_c": 8.9,
              "windchill_f": 47.9,
              "heatindex_c": 10.9,
              "heatindex_f": 51.5,
              "dewpoint_c": 8.9,
              "dewpoint_f": 47.9,
              "will_it_rain": 0,
              "chance_of_rain": 57,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 15.7,
              "gust_kph": 25.2,
              "uv": 1
            },
            {
              "time_epoch": 1698472800,
              "time": "2023-10-28 07:00",
              "temp_c": 10.6,
              "temp_f": 51.1,
              "is_day": 0,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                "code": 1063
              },
              "wind_mph": 8.7,
              "wind_kph": 14,
              "wind_degree": 222,
              "wind_dir": "SW",
              "pressure_mb": 991,
              "pressure_in": 29.25,
              "precip_mm": 0.03,
              "precip_in": 0,
              "humidity": 88,
              "cloud": 58,
              "feelslike_c": 8.8,
              "feelslike_f": 47.9,
              "windchill_c": 8.8,
              "windchill_f": 47.9,
              "heatindex_c": 10.6,
              "heatindex_f": 51.1,
              "dewpoint_c": 8.8,
              "dewpoint_f": 47.8,
              "will_it_rain": 0,
              "chance_of_rain": 70,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14,
              "gust_kph": 22.6,
              "uv": 1
            },
            {
              "time_epoch": 1698476400,
              "time": "2023-10-28 08:00",
              "temp_c": 11.2,
              "temp_f": 52.1,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 8.9,
              "wind_kph": 14.4,
              "wind_degree": 217,
              "wind_dir": "SW",
              "pressure_mb": 991,
              "pressure_in": 29.27,
              "precip_mm": 0.01,
              "precip_in": 0,
              "humidity": 85,
              "cloud": 100,
              "feelslike_c": 9.4,
              "feelslike_f": 48.9,
              "windchill_c": 9.4,
              "windchill_f": 48.9,
              "heatindex_c": 11.2,
              "heatindex_f": 52.1,
              "dewpoint_c": 8.8,
              "dewpoint_f": 47.8,
              "will_it_rain": 1,
              "chance_of_rain": 85,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 13.8,
              "gust_kph": 22.3,
              "uv": 3
            },
            {
              "time_epoch": 1698480000,
              "time": "2023-10-28 09:00",
              "temp_c": 11.8,
              "temp_f": 53.2,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 8.7,
              "wind_kph": 14,
              "wind_degree": 207,
              "wind_dir": "SSW",
              "pressure_mb": 991,
              "pressure_in": 29.28,
              "precip_mm": 0.02,
              "precip_in": 0,
              "humidity": 82,
              "cloud": 79,
              "feelslike_c": 10.2,
              "feelslike_f": 50.4,
              "windchill_c": 10.2,
              "windchill_f": 50.4,
              "heatindex_c": 11.8,
              "heatindex_f": 53.2,
              "dewpoint_c": 8.8,
              "dewpoint_f": 47.8,
              "will_it_rain": 1,
              "chance_of_rain": 87,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 13.2,
              "gust_kph": 21.2,
              "uv": 3
            },
            {
              "time_epoch": 1698483600,
              "time": "2023-10-28 10:00",
              "temp_c": 13.1,
              "temp_f": 55.5,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 9.6,
              "wind_kph": 15.5,
              "wind_degree": 209,
              "wind_dir": "SSW",
              "pressure_mb": 992,
              "pressure_in": 29.28,
              "precip_mm": 0.06,
              "precip_in": 0,
              "humidity": 77,
              "cloud": 89,
              "feelslike_c": 11.7,
              "feelslike_f": 53,
              "windchill_c": 11.7,
              "windchill_f": 53,
              "heatindex_c": 13.1,
              "heatindex_f": 55.5,
              "dewpoint_c": 9.1,
              "dewpoint_f": 48.3,
              "will_it_rain": 1,
              "chance_of_rain": 88,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 13.1,
              "gust_kph": 21,
              "uv": 3
            },
            {
              "time_epoch": 1698487200,
              "time": "2023-10-28 11:00",
              "temp_c": 13.9,
              "temp_f": 57,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 11,
              "wind_kph": 17.6,
              "wind_degree": 211,
              "wind_dir": "SSW",
              "pressure_mb": 992,
              "pressure_in": 29.29,
              "precip_mm": 0.11,
              "precip_in": 0,
              "humidity": 72,
              "cloud": 89,
              "feelslike_c": 12.5,
              "feelslike_f": 54.4,
              "windchill_c": 12.5,
              "windchill_f": 54.4,
              "heatindex_c": 13.9,
              "heatindex_f": 57,
              "dewpoint_c": 8.9,
              "dewpoint_f": 47.9,
              "will_it_rain": 0,
              "chance_of_rain": 65,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.4,
              "gust_kph": 23.2,
              "uv": 3
            },
            {
              "time_epoch": 1698490800,
              "time": "2023-10-28 12:00",
              "temp_c": 14.6,
              "temp_f": 58.3,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 11,
              "wind_kph": 17.6,
              "wind_degree": 202,
              "wind_dir": "SSW",
              "pressure_mb": 991,
              "pressure_in": 29.28,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 67,
              "cloud": 16,
              "feelslike_c": 13.3,
              "feelslike_f": 56,
              "windchill_c": 13.3,
              "windchill_f": 56,
              "heatindex_c": 14.6,
              "heatindex_f": 58.3,
              "dewpoint_c": 8.5,
              "dewpoint_f": 47.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 13.9,
              "gust_kph": 22.3,
              "uv": 4
            },
            {
              "time_epoch": 1698494400,
              "time": "2023-10-28 13:00",
              "temp_c": 14.6,
              "temp_f": 58.3,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 11.6,
              "wind_kph": 18.7,
              "wind_degree": 195,
              "wind_dir": "SSW",
              "pressure_mb": 991,
              "pressure_in": 29.28,
              "precip_mm": 0.03,
              "precip_in": 0,
              "humidity": 68,
              "cloud": 70,
              "feelslike_c": 13.3,
              "feelslike_f": 55.9,
              "windchill_c": 13.3,
              "windchill_f": 55.9,
              "heatindex_c": 14.6,
              "heatindex_f": 58.3,
              "dewpoint_c": 8.8,
              "dewpoint_f": 47.8,
              "will_it_rain": 0,
              "chance_of_rain": 66,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.3,
              "gust_kph": 23.1,
              "uv": 3
            },
            {
              "time_epoch": 1698498000,
              "time": "2023-10-28 14:00",
              "temp_c": 14.4,
              "temp_f": 57.9,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 11.2,
              "wind_kph": 18,
              "wind_degree": 186,
              "wind_dir": "S",
              "pressure_mb": 991,
              "pressure_in": 29.25,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 70,
              "cloud": 23,
              "feelslike_c": 13.1,
              "feelslike_f": 55.5,
              "windchill_c": 13.1,
              "windchill_f": 55.5,
              "heatindex_c": 14.4,
              "heatindex_f": 57.9,
              "dewpoint_c": 8.9,
              "dewpoint_f": 48.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 13.9,
              "gust_kph": 22.3,
              "uv": 4
            },
            {
              "time_epoch": 1698501600,
              "time": "2023-10-28 15:00",
              "temp_c": 13.8,
              "temp_f": 56.9,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 10.7,
              "wind_kph": 17.3,
              "wind_degree": 175,
              "wind_dir": "S",
              "pressure_mb": 990,
              "pressure_in": 29.23,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 72,
              "cloud": 27,
              "feelslike_c": 12.4,
              "feelslike_f": 54.4,
              "windchill_c": 12.4,
              "windchill_f": 54.4,
              "heatindex_c": 13.8,
              "heatindex_f": 56.9,
              "dewpoint_c": 9,
              "dewpoint_f": 48.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.1,
              "gust_kph": 22.7,
              "uv": 4
            },
            {
              "time_epoch": 1698505200,
              "time": "2023-10-28 16:00",
              "temp_c": 13.3,
              "temp_f": 55.9,
              "is_day": 1,
              "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                "code": 1006
              },
              "wind_mph": 10.7,
              "wind_kph": 17.3,
              "wind_degree": 157,
              "wind_dir": "SSE",
              "pressure_mb": 989,
              "pressure_in": 29.21,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 77,
              "cloud": 71,
              "feelslike_c": 11.8,
              "feelslike_f": 53.2,
              "windchill_c": 11.8,
              "windchill_f": 53.2,
              "heatindex_c": 13.3,
              "heatindex_f": 55.9,
              "dewpoint_c": 9.3,
              "dewpoint_f": 48.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 15.3,
              "gust_kph": 24.7,
              "uv": 3
            },
            {
              "time_epoch": 1698508800,
              "time": "2023-10-28 17:00",
              "temp_c": 12.8,
              "temp_f": 55,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 11.6,
              "wind_kph": 18.7,
              "wind_degree": 137,
              "wind_dir": "SE",
              "pressure_mb": 988,
              "pressure_in": 29.17,
              "precip_mm": 0.01,
              "precip_in": 0,
              "humidity": 80,
              "cloud": 90,
              "feelslike_c": 11,
              "feelslike_f": 51.8,
              "windchill_c": 11,
              "windchill_f": 51.8,
              "heatindex_c": 12.8,
              "heatindex_f": 55,
              "dewpoint_c": 9.4,
              "dewpoint_f": 48.9,
              "will_it_rain": 1,
              "chance_of_rain": 72,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 17.5,
              "gust_kph": 28.2,
              "uv": 3
            },
            {
              "time_epoch": 1698512400,
              "time": "2023-10-28 18:00",
              "temp_c": 12.6,
              "temp_f": 54.7,
              "is_day": 0,
              "condition": {
                "text": "Light rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
                "code": 1183
              },
              "wind_mph": 14.8,
              "wind_kph": 23.8,
              "wind_degree": 140,
              "wind_dir": "SE",
              "pressure_mb": 987,
              "pressure_in": 29.14,
              "precip_mm": 1.5,
              "precip_in": 0.06,
              "humidity": 86,
              "cloud": 100,
              "feelslike_c": 10.4,
              "feelslike_f": 50.7,
              "windchill_c": 10.4,
              "windchill_f": 50.7,
              "heatindex_c": 12.6,
              "heatindex_f": 54.7,
              "dewpoint_c": 10.3,
              "dewpoint_f": 50.5,
              "will_it_rain": 1,
              "chance_of_rain": 85,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 21.1,
              "gust_kph": 34,
              "uv": 1
            },
            {
              "time_epoch": 1698516000,
              "time": "2023-10-28 19:00",
              "temp_c": 13,
              "temp_f": 55.4,
              "is_day": 0,
              "condition": {
                "text": "Light drizzle",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                "code": 1153
              },
              "wind_mph": 18.8,
              "wind_kph": 30.2,
              "wind_degree": 152,
              "wind_dir": "SSE",
              "pressure_mb": 985,
              "pressure_in": 29.1,
              "precip_mm": 0.7,
              "precip_in": 0.03,
              "humidity": 89,
              "cloud": 100,
              "feelslike_c": 10.5,
              "feelslike_f": 50.9,
              "windchill_c": 10.5,
              "windchill_f": 50.9,
              "heatindex_c": 13,
              "heatindex_f": 55.4,
              "dewpoint_c": 11.2,
              "dewpoint_f": 52.1,
              "will_it_rain": 1,
              "chance_of_rain": 85,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 27,
              "gust_kph": 43.5,
              "uv": 1
            },
            {
              "time_epoch": 1698519600,
              "time": "2023-10-28 20:00",
              "temp_c": 13.6,
              "temp_f": 56.5,
              "is_day": 0,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                "code": 1240
              },
              "wind_mph": 17,
              "wind_kph": 27.4,
              "wind_degree": 175,
              "wind_dir": "S",
              "pressure_mb": 985,
              "pressure_in": 29.08,
              "precip_mm": 0.45,
              "precip_in": 0.02,
              "humidity": 86,
              "cloud": 100,
              "feelslike_c": 11.4,
              "feelslike_f": 52.6,
              "windchill_c": 11.4,
              "windchill_f": 52.6,
              "heatindex_c": 13.6,
              "heatindex_f": 56.5,
              "dewpoint_c": 11.3,
              "dewpoint_f": 52.4,
              "will_it_rain": 1,
              "chance_of_rain": 83,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 25.3,
              "gust_kph": 40.6,
              "uv": 1
            },
            {
              "time_epoch": 1698523200,
              "time": "2023-10-28 21:00",
              "temp_c": 13.5,
              "temp_f": 56.3,
              "is_day": 0,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                "code": 1240
              },
              "wind_mph": 18.8,
              "wind_kph": 30.2,
              "wind_degree": 196,
              "wind_dir": "SSW",
              "pressure_mb": 985,
              "pressure_in": 29.09,
              "precip_mm": 0.96,
              "precip_in": 0.04,
              "humidity": 81,
              "cloud": 88,
              "feelslike_c": 11.1,
              "feelslike_f": 52,
              "windchill_c": 11.1,
              "windchill_f": 52,
              "heatindex_c": 13.5,
              "heatindex_f": 56.3,
              "dewpoint_c": 10.3,
              "dewpoint_f": 50.6,
              "will_it_rain": 1,
              "chance_of_rain": 84,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 28,
              "gust_kph": 45.1,
              "uv": 1
            },
            {
              "time_epoch": 1698526800,
              "time": "2023-10-28 22:00",
              "temp_c": 13,
              "temp_f": 55.4,
              "is_day": 0,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                "code": 1063
              },
              "wind_mph": 16.6,
              "wind_kph": 26.6,
              "wind_degree": 200,
              "wind_dir": "SSW",
              "pressure_mb": 984,
              "pressure_in": 29.07,
              "precip_mm": 0.21,
              "precip_in": 0.01,
              "humidity": 82,
              "cloud": 82,
              "feelslike_c": 10.7,
              "feelslike_f": 51.2,
              "windchill_c": 10.7,
              "windchill_f": 51.2,
              "heatindex_c": 13,
              "heatindex_f": 55.4,
              "dewpoint_c": 10.1,
              "dewpoint_f": 50.2,
              "will_it_rain": 0,
              "chance_of_rain": 57,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 25.1,
              "gust_kph": 40.4,
              "uv": 1
            },
            {
              "time_epoch": 1698530400,
              "time": "2023-10-28 23:00",
              "temp_c": 12.3,
              "temp_f": 54.1,
              "is_day": 0,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                "code": 1063
              },
              "wind_mph": 15.4,
              "wind_kph": 24.8,
              "wind_degree": 202,
              "wind_dir": "SSW",
              "pressure_mb": 985,
              "pressure_in": 29.08,
              "precip_mm": 0.01,
              "precip_in": 0,
              "humidity": 82,
              "cloud": 89,
              "feelslike_c": 9.8,
              "feelslike_f": 49.7,
              "windchill_c": 9.8,
              "windchill_f": 49.7,
              "heatindex_c": 12.3,
              "heatindex_f": 54.1,
              "dewpoint_c": 9.3,
              "dewpoint_f": 48.8,
              "will_it_rain": 1,
              "chance_of_rain": 77,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 23.2,
              "gust_kph": 37.3,
              "uv": 1
            }
          ]
        },
        {
          "date": "2023-10-29",
          "date_epoch": 1698537600,
          "day": {
            "maxtemp_c": 12.9,
            "maxtemp_f": 55.3,
            "mintemp_c": 10.9,
            "mintemp_f": 51.5,
            "avgtemp_c": 12,
            "avgtemp_f": 53.6,
            "maxwind_mph": 19.2,
            "maxwind_kph": 31,
            "totalprecip_mm": 3.98,
            "totalprecip_in": 0.16,
            "totalsnow_cm": 0,
            "avgvis_km": 9.7,
            "avgvis_miles": 6,
            "avghumidity": 76,
            "daily_will_it_rain": 1,
            "daily_chance_of_rain": 89,
            "daily_will_it_snow": 0,
            "daily_chance_of_snow": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "uv": 3
          },
          "astro": {
            "sunrise": "07:48 AM",
            "sunset": "05:40 PM",
            "moonrise": "05:45 PM",
            "moonset": "08:34 AM",
            "moon_phase": "Waning Gibbous",
            "moon_illumination": 100,
            "is_moon_up": 1,
            "is_sun_up": 0
          },
          "hour": [
            {
              "time_epoch": 1698534000,
              "time": "2023-10-29 00:00",
              "temp_c": 12,
              "temp_f": 53.6,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 14.8,
              "wind_kph": 23.8,
              "wind_degree": 205,
              "wind_dir": "SSW",
              "pressure_mb": 985,
              "pressure_in": 29.09,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 82,
              "cloud": 53,
              "feelslike_c": 9.6,
              "feelslike_f": 49.2,
              "windchill_c": 9.6,
              "windchill_f": 49.2,
              "heatindex_c": 12,
              "heatindex_f": 53.6,
              "dewpoint_c": 9,
              "dewpoint_f": 48.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 22.4,
              "gust_kph": 36,
              "uv": 1
            },
            {
              "time_epoch": 1698537600,
              "time": "2023-10-29 01:00",
              "temp_c": 11.6,
              "temp_f": 52.9,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 12.8,
              "wind_kph": 20.5,
              "wind_degree": 210,
              "wind_dir": "SSW",
              "pressure_mb": 985,
              "pressure_in": 29.1,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 79,
              "cloud": 29,
              "feelslike_c": 9.4,
              "feelslike_f": 48.9,
              "windchill_c": 9.4,
              "windchill_f": 48.9,
              "heatindex_c": 11.6,
              "heatindex_f": 53,
              "dewpoint_c": 8.1,
              "dewpoint_f": 46.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 19.9,
              "gust_kph": 32,
              "uv": 1
            },
            {
              "time_epoch": 1698541200,
              "time": "2023-10-29 02:00",
              "temp_c": 11.4,
              "temp_f": 52.5,
              "is_day": 0,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                "code": 1063
              },
              "wind_mph": 9.8,
              "wind_kph": 15.8,
              "wind_degree": 197,
              "wind_dir": "SSW",
              "pressure_mb": 985,
              "pressure_in": 29.09,
              "precip_mm": 0.01,
              "precip_in": 0,
              "humidity": 81,
              "cloud": 76,
              "feelslike_c": 9.5,
              "feelslike_f": 49.2,
              "windchill_c": 9.5,
              "windchill_f": 49.2,
              "heatindex_c": 11.4,
              "heatindex_f": 52.5,
              "dewpoint_c": 8.3,
              "dewpoint_f": 46.9,
              "will_it_rain": 1,
              "chance_of_rain": 75,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 15.5,
              "gust_kph": 24.9,
              "uv": 1
            },
            {
              "time_epoch": 1698544800,
              "time": "2023-10-29 03:00",
              "temp_c": 11.4,
              "temp_f": 52.5,
              "is_day": 0,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                "code": 1063
              },
              "wind_mph": 9.4,
              "wind_kph": 15.1,
              "wind_degree": 201,
              "wind_dir": "SSW",
              "pressure_mb": 985,
              "pressure_in": 29.09,
              "precip_mm": 0.08,
              "precip_in": 0,
              "humidity": 82,
              "cloud": 83,
              "feelslike_c": 9.6,
              "feelslike_f": 49.3,
              "windchill_c": 9.6,
              "windchill_f": 49.3,
              "heatindex_c": 11.4,
              "heatindex_f": 52.5,
              "dewpoint_c": 8.4,
              "dewpoint_f": 47.1,
              "will_it_rain": 0,
              "chance_of_rain": 66,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.9,
              "gust_kph": 24,
              "uv": 1
            },
            {
              "time_epoch": 1698548400,
              "time": "2023-10-29 04:00",
              "temp_c": 11.3,
              "temp_f": 52.4,
              "is_day": 0,
              "condition": {
                "text": "Patchy light drizzle",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/263.png",
                "code": 1150
              },
              "wind_mph": 8.9,
              "wind_kph": 14.4,
              "wind_degree": 208,
              "wind_dir": "SSW",
              "pressure_mb": 985,
              "pressure_in": 29.09,
              "precip_mm": 0.19,
              "precip_in": 0.01,
              "humidity": 80,
              "cloud": 77,
              "feelslike_c": 9.6,
              "feelslike_f": 49.3,
              "windchill_c": 9.6,
              "windchill_f": 49.3,
              "heatindex_c": 11.3,
              "heatindex_f": 52.4,
              "dewpoint_c": 8,
              "dewpoint_f": 46.3,
              "will_it_rain": 0,
              "chance_of_rain": 50,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 5,
              "vis_miles": 3,
              "gust_mph": 13.7,
              "gust_kph": 22.1,
              "uv": 1
            },
            {
              "time_epoch": 1698552000,
              "time": "2023-10-29 05:00",
              "temp_c": 10.9,
              "temp_f": 51.5,
              "is_day": 0,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                "code": 1240
              },
              "wind_mph": 11,
              "wind_kph": 17.6,
              "wind_degree": 204,
              "wind_dir": "SSW",
              "pressure_mb": 986,
              "pressure_in": 29.11,
              "precip_mm": 0.21,
              "precip_in": 0.01,
              "humidity": 82,
              "cloud": 100,
              "feelslike_c": 8.7,
              "feelslike_f": 47.6,
              "windchill_c": 8.7,
              "windchill_f": 47.6,
              "heatindex_c": 10.9,
              "heatindex_f": 51.5,
              "dewpoint_c": 8,
              "dewpoint_f": 46.4,
              "will_it_rain": 1,
              "chance_of_rain": 89,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 16.8,
              "gust_kph": 27,
              "uv": 1
            },
            {
              "time_epoch": 1698555600,
              "time": "2023-10-29 06:00",
              "temp_c": 11.3,
              "temp_f": 52.3,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 11.4,
              "wind_kph": 18.4,
              "wind_degree": 224,
              "wind_dir": "SW",
              "pressure_mb": 986,
              "pressure_in": 29.12,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 76,
              "cloud": 28,
              "feelslike_c": 9.2,
              "feelslike_f": 48.5,
              "windchill_c": 9.2,
              "windchill_f": 48.5,
              "heatindex_c": 11.3,
              "heatindex_f": 52.3,
              "dewpoint_c": 7.3,
              "dewpoint_f": 45.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 17.4,
              "gust_kph": 27.9,
              "uv": 1
            },
            {
              "time_epoch": 1698559200,
              "time": "2023-10-29 07:00",
              "temp_c": 11,
              "temp_f": 51.8,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 12.3,
              "wind_kph": 19.8,
              "wind_degree": 217,
              "wind_dir": "SW",
              "pressure_mb": 987,
              "pressure_in": 29.16,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 76,
              "cloud": 25,
              "feelslike_c": 8.7,
              "feelslike_f": 47.6,
              "windchill_c": 8.7,
              "windchill_f": 47.6,
              "heatindex_c": 11,
              "heatindex_f": 51.8,
              "dewpoint_c": 7,
              "dewpoint_f": 44.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 19.2,
              "gust_kph": 30.9,
              "uv": 1
            },
            {
              "time_epoch": 1698562800,
              "time": "2023-10-29 08:00",
              "temp_c": 11.4,
              "temp_f": 52.5,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 12.1,
              "wind_kph": 19.4,
              "wind_degree": 213,
              "wind_dir": "SSW",
              "pressure_mb": 988,
              "pressure_in": 29.19,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 72,
              "cloud": 31,
              "feelslike_c": 9.2,
              "feelslike_f": 48.5,
              "windchill_c": 9.2,
              "windchill_f": 48.5,
              "heatindex_c": 11.4,
              "heatindex_f": 52.5,
              "dewpoint_c": 6.6,
              "dewpoint_f": 43.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 18.5,
              "gust_kph": 29.8,
              "uv": 4
            },
            {
              "time_epoch": 1698566400,
              "time": "2023-10-29 09:00",
              "temp_c": 12.3,
              "temp_f": 54.2,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 11.6,
              "wind_kph": 18.7,
              "wind_degree": 209,
              "wind_dir": "SSW",
              "pressure_mb": 989,
              "pressure_in": 29.2,
              "precip_mm": 0.03,
              "precip_in": 0,
              "humidity": 68,
              "cloud": 76,
              "feelslike_c": 10.4,
              "feelslike_f": 50.7,
              "windchill_c": 10.4,
              "windchill_f": 50.7,
              "heatindex_c": 12.3,
              "heatindex_f": 54.2,
              "dewpoint_c": 6.6,
              "dewpoint_f": 44,
              "will_it_rain": 1,
              "chance_of_rain": 89,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 16.4,
              "gust_kph": 26.4,
              "uv": 3
            },
            {
              "time_epoch": 1698570000,
              "time": "2023-10-29 10:00",
              "temp_c": 12.9,
              "temp_f": 55.2,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 13.2,
              "wind_kph": 21.2,
              "wind_degree": 202,
              "wind_dir": "SSW",
              "pressure_mb": 990,
              "pressure_in": 29.22,
              "precip_mm": 0.35,
              "precip_in": 0.01,
              "humidity": 70,
              "cloud": 59,
              "feelslike_c": 10.9,
              "feelslike_f": 51.6,
              "windchill_c": 10.9,
              "windchill_f": 51.6,
              "heatindex_c": 12.9,
              "heatindex_f": 55.2,
              "dewpoint_c": 7.5,
              "dewpoint_f": 45.5,
              "will_it_rain": 1,
              "chance_of_rain": 80,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 17.5,
              "gust_kph": 28.2,
              "uv": 3
            },
            {
              "time_epoch": 1698573600,
              "time": "2023-10-29 11:00",
              "temp_c": 12.8,
              "temp_f": 55.1,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 14.1,
              "wind_kph": 22.7,
              "wind_degree": 200,
              "wind_dir": "SSW",
              "pressure_mb": 989,
              "pressure_in": 29.22,
              "precip_mm": 0.41,
              "precip_in": 0.02,
              "humidity": 72,
              "cloud": 63,
              "feelslike_c": 10.8,
              "feelslike_f": 51.4,
              "windchill_c": 10.8,
              "windchill_f": 51.4,
              "heatindex_c": 12.8,
              "heatindex_f": 55.1,
              "dewpoint_c": 8,
              "dewpoint_f": 46.4,
              "will_it_rain": 0,
              "chance_of_rain": 63,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 17.8,
              "gust_kph": 28.6,
              "uv": 3
            },
            {
              "time_epoch": 1698577200,
              "time": "2023-10-29 12:00",
              "temp_c": 12.9,
              "temp_f": 55.3,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 16.3,
              "wind_kph": 26.3,
              "wind_degree": 201,
              "wind_dir": "SSW",
              "pressure_mb": 989,
              "pressure_in": 29.22,
              "precip_mm": 0.74,
              "precip_in": 0.03,
              "humidity": 72,
              "cloud": 96,
              "feelslike_c": 10.6,
              "feelslike_f": 51.2,
              "windchill_c": 10.6,
              "windchill_f": 51.2,
              "heatindex_c": 12.9,
              "heatindex_f": 55.3,
              "dewpoint_c": 8,
              "dewpoint_f": 46.4,
              "will_it_rain": 1,
              "chance_of_rain": 79,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 22.1,
              "gust_kph": 35.5,
              "uv": 3
            },
            {
              "time_epoch": 1698580800,
              "time": "2023-10-29 13:00",
              "temp_c": 12.7,
              "temp_f": 54.8,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 14.5,
              "wind_kph": 23.4,
              "wind_degree": 204,
              "wind_dir": "SSW",
              "pressure_mb": 989,
              "pressure_in": 29.21,
              "precip_mm": 0.36,
              "precip_in": 0.01,
              "humidity": 74,
              "cloud": 100,
              "feelslike_c": 10.5,
              "feelslike_f": 50.8,
              "windchill_c": 10.5,
              "windchill_f": 50.8,
              "heatindex_c": 12.7,
              "heatindex_f": 54.8,
              "dewpoint_c": 8.1,
              "dewpoint_f": 46.5,
              "will_it_rain": 0,
              "chance_of_rain": 53,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 19.2,
              "gust_kph": 31,
              "uv": 3
            },
            {
              "time_epoch": 1698584400,
              "time": "2023-10-29 14:00",
              "temp_c": 12.7,
              "temp_f": 54.9,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 14.3,
              "wind_kph": 23,
              "wind_degree": 205,
              "wind_dir": "SSW",
              "pressure_mb": 989,
              "pressure_in": 29.21,
              "precip_mm": 0.31,
              "precip_in": 0.01,
              "humidity": 74,
              "cloud": 70,
              "feelslike_c": 10.6,
              "feelslike_f": 51.1,
              "windchill_c": 10.6,
              "windchill_f": 51.1,
              "heatindex_c": 12.7,
              "heatindex_f": 54.9,
              "dewpoint_c": 8.2,
              "dewpoint_f": 46.8,
              "will_it_rain": 1,
              "chance_of_rain": 76,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 18.8,
              "gust_kph": 30.2,
              "uv": 3
            },
            {
              "time_epoch": 1698588000,
              "time": "2023-10-29 15:00",
              "temp_c": 12.8,
              "temp_f": 55,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 14.5,
              "wind_kph": 23.4,
              "wind_degree": 203,
              "wind_dir": "SSW",
              "pressure_mb": 989,
              "pressure_in": 29.21,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 70,
              "cloud": 54,
              "feelslike_c": 10.6,
              "feelslike_f": 51.1,
              "windchill_c": 10.6,
              "windchill_f": 51.1,
              "heatindex_c": 12.8,
              "heatindex_f": 55,
              "dewpoint_c": 7.5,
              "dewpoint_f": 45.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 20.1,
              "gust_kph": 32.3,
              "uv": 4
            },
            {
              "time_epoch": 1698591600,
              "time": "2023-10-29 16:00",
              "temp_c": 12.1,
              "temp_f": 53.9,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 17,
              "wind_kph": 27.4,
              "wind_degree": 201,
              "wind_dir": "SSW",
              "pressure_mb": 990,
              "pressure_in": 29.22,
              "precip_mm": 0.29,
              "precip_in": 0.01,
              "humidity": 74,
              "cloud": 100,
              "feelslike_c": 9.5,
              "feelslike_f": 49.2,
              "windchill_c": 9.5,
              "windchill_f": 49.2,
              "heatindex_c": 12.2,
              "heatindex_f": 53.9,
              "dewpoint_c": 7.6,
              "dewpoint_f": 45.6,
              "will_it_rain": 0,
              "chance_of_rain": 56,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 24.4,
              "gust_kph": 39.3,
              "uv": 3
            },
            {
              "time_epoch": 1698595200,
              "time": "2023-10-29 17:00",
              "temp_c": 11.9,
              "temp_f": 53.5,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 19.2,
              "wind_kph": 31,
              "wind_degree": 205,
              "wind_dir": "SSW",
              "pressure_mb": 990,
              "pressure_in": 29.24,
              "precip_mm": 0.78,
              "precip_in": 0.03,
              "humidity": 78,
              "cloud": 100,
              "feelslike_c": 9.1,
              "feelslike_f": 48.3,
              "windchill_c": 9.1,
              "windchill_f": 48.3,
              "heatindex_c": 11.9,
              "heatindex_f": 53.5,
              "dewpoint_c": 8.3,
              "dewpoint_f": 46.9,
              "will_it_rain": 1,
              "chance_of_rain": 77,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 27.5,
              "gust_kph": 44.2,
              "uv": 3
            },
            {
              "time_epoch": 1698598800,
              "time": "2023-10-29 18:00",
              "temp_c": 12.1,
              "temp_f": 53.9,
              "is_day": 0,
              "condition": {
                "text": "Thundery outbreaks possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/200.png",
                "code": 1087
              },
              "wind_mph": 16.6,
              "wind_kph": 26.6,
              "wind_degree": 206,
              "wind_dir": "SSW",
              "pressure_mb": 991,
              "pressure_in": 29.27,
              "precip_mm": 0.11,
              "precip_in": 0,
              "humidity": 77,
              "cloud": 100,
              "feelslike_c": 9.6,
              "feelslike_f": 49.2,
              "windchill_c": 9.6,
              "windchill_f": 49.2,
              "heatindex_c": 12.1,
              "heatindex_f": 53.9,
              "dewpoint_c": 8.3,
              "dewpoint_f": 46.9,
              "will_it_rain": 1,
              "chance_of_rain": 77,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 24.9,
              "gust_kph": 40.1,
              "uv": 1
            },
            {
              "time_epoch": 1698602400,
              "time": "2023-10-29 19:00",
              "temp_c": 12.4,
              "temp_f": 54.3,
              "is_day": 0,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                "code": 1063
              },
              "wind_mph": 19,
              "wind_kph": 30.6,
              "wind_degree": 205,
              "wind_dir": "SSW",
              "pressure_mb": 992,
              "pressure_in": 29.29,
              "precip_mm": 0.03,
              "precip_in": 0,
              "humidity": 75,
              "cloud": 81,
              "feelslike_c": 9.7,
              "feelslike_f": 49.4,
              "windchill_c": 9.7,
              "windchill_f": 49.4,
              "heatindex_c": 12.4,
              "heatindex_f": 54.4,
              "dewpoint_c": 8,
              "dewpoint_f": 46.5,
              "will_it_rain": 0,
              "chance_of_rain": 53,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 28.4,
              "gust_kph": 45.8,
              "uv": 1
            },
            {
              "time_epoch": 1698606000,
              "time": "2023-10-29 20:00",
              "temp_c": 12.2,
              "temp_f": 53.9,
              "is_day": 0,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                "code": 1063
              },
              "wind_mph": 17.2,
              "wind_kph": 27.7,
              "wind_degree": 209,
              "wind_dir": "SSW",
              "pressure_mb": 993,
              "pressure_in": 29.31,
              "precip_mm": 0.05,
              "precip_in": 0,
              "humidity": 77,
              "cloud": 100,
              "feelslike_c": 9.6,
              "feelslike_f": 49.2,
              "windchill_c": 9.6,
              "windchill_f": 49.2,
              "heatindex_c": 12.2,
              "heatindex_f": 53.9,
              "dewpoint_c": 8.2,
              "dewpoint_f": 46.8,
              "will_it_rain": 0,
              "chance_of_rain": 66,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 25.9,
              "gust_kph": 41.7,
              "uv": 1
            },
            {
              "time_epoch": 1698609600,
              "time": "2023-10-29 21:00",
              "temp_c": 12.1,
              "temp_f": 53.7,
              "is_day": 0,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                "code": 1063
              },
              "wind_mph": 16.6,
              "wind_kph": 26.6,
              "wind_degree": 208,
              "wind_dir": "SSW",
              "pressure_mb": 993,
              "pressure_in": 29.33,
              "precip_mm": 0.02,
              "precip_in": 0,
              "humidity": 76,
              "cloud": 82,
              "feelslike_c": 9.5,
              "feelslike_f": 49.1,
              "windchill_c": 9.5,
              "windchill_f": 49.1,
              "heatindex_c": 12.1,
              "heatindex_f": 53.7,
              "dewpoint_c": 7.9,
              "dewpoint_f": 46.2,
              "will_it_rain": 1,
              "chance_of_rain": 87,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 25.3,
              "gust_kph": 40.7,
              "uv": 1
            },
            {
              "time_epoch": 1698613200,
              "time": "2023-10-29 22:00",
              "temp_c": 11.9,
              "temp_f": 53.4,
              "is_day": 0,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                "code": 1063
              },
              "wind_mph": 16.1,
              "wind_kph": 25.9,
              "wind_degree": 206,
              "wind_dir": "SSW",
              "pressure_mb": 994,
              "pressure_in": 29.35,
              "precip_mm": 0.03,
              "precip_in": 0,
              "humidity": 75,
              "cloud": 60,
              "feelslike_c": 9.3,
              "feelslike_f": 48.8,
              "windchill_c": 9.3,
              "windchill_f": 48.8,
              "heatindex_c": 11.9,
              "heatindex_f": 53.4,
              "dewpoint_c": 7.6,
              "dewpoint_f": 45.7,
              "will_it_rain": 0,
              "chance_of_rain": 61,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 24.9,
              "gust_kph": 40.1,
              "uv": 1
            },
            {
              "time_epoch": 1698616800,
              "time": "2023-10-29 23:00",
              "temp_c": 11.7,
              "temp_f": 53.1,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 14.1,
              "wind_kph": 22.7,
              "wind_degree": 206,
              "wind_dir": "SSW",
              "pressure_mb": 994,
              "pressure_in": 29.36,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 75,
              "cloud": 51,
              "feelslike_c": 9.3,
              "feelslike_f": 48.8,
              "windchill_c": 9.3,
              "windchill_f": 48.8,
              "heatindex_c": 11.7,
              "heatindex_f": 53.1,
              "dewpoint_c": 7.5,
              "dewpoint_f": 45.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 22.1,
              "gust_kph": 35.5,
              "uv": 1
            }
          ]
        }
      ]
    }
  }

  
export default data