const hourData = {
    "location": {
      "name": "London",
      "region": "City of London, Greater London",
      "country": "United Kingdom",
      "lat": 51.52,
      "lon": -0.11,
      "tz_id": "Europe/London",
      "localtime_epoch": 1697838147,
      "localtime": "2023-10-20 22:42"
    },
    "forecast": {
      "forecastday": [
        {
          "date": "2023-10-20",
          "date_epoch": 1697760000,
          "day": {
            "maxtemp_c": 14.7,
            "maxtemp_f": 58.5,
            "mintemp_c": 11.6,
            "mintemp_f": 52.9,
            "avgtemp_c": 14,
            "avgtemp_f": 57.2,
            "maxwind_mph": 19,
            "maxwind_kph": 30.6,
            "totalprecip_mm": 38.55,
            "totalprecip_in": 1.52,
            "avgvis_km": 7.8,
            "avgvis_miles": 4,
            "avghumidity": 91,
            "condition": {
              "text": "Light rain shower",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
              "code": 1240
            },
            "uv": 3
          },
          "astro": {
            "sunrise": "07:33 AM",
            "sunset": "05:57 PM",
            "moonrise": "02:27 PM",
            "moonset": "09:00 PM",
            "moon_phase": "Waxing Crescent",
            "moon_illumination": "27"
          },
          "hour": [
            {
              "time_epoch": 1697756400,
              "time": "2023-10-20 00:00",
              "temp_c": 14.2,
              "temp_f": 57.5,
              "is_day": 0,
              "condition": {
                "text": "Light rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
                "code": 1183
              },
              "wind_mph": 4.9,
              "wind_kph": 7.9,
              "wind_degree": 51,
              "wind_dir": "NE",
              "pressure_mb": 982,
              "pressure_in": 28.98,
              "precip_mm": 1.86,
              "precip_in": 0.07,
              "humidity": 95,
              "cloud": 100,
              "feelslike_c": 13.9,
              "feelslike_f": 57.1,
              "windchill_c": 13.9,
              "windchill_f": 57.1,
              "heatindex_c": 14.2,
              "heatindex_f": 57.5,
              "dewpoint_c": 13.4,
              "dewpoint_f": 56.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 7.1,
              "gust_kph": 11.4,
              "uv": 1
            },
            {
              "time_epoch": 1697760000,
              "time": "2023-10-20 01:00",
              "temp_c": 14.2,
              "temp_f": 57.5,
              "is_day": 0,
              "condition": {
                "text": "Light drizzle",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                "code": 1153
              },
              "wind_mph": 8.3,
              "wind_kph": 13.3,
              "wind_degree": 47,
              "wind_dir": "NE",
              "pressure_mb": 980,
              "pressure_in": 28.95,
              "precip_mm": 0.49,
              "precip_in": 0.02,
              "humidity": 95,
              "cloud": 95,
              "feelslike_c": 13.2,
              "feelslike_f": 55.8,
              "windchill_c": 13.2,
              "windchill_f": 55.8,
              "heatindex_c": 14.2,
              "heatindex_f": 57.5,
              "dewpoint_c": 13.3,
              "dewpoint_f": 56,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 12.3,
              "gust_kph": 19.8,
              "uv": 1
            },
            {
              "time_epoch": 1697763600,
              "time": "2023-10-20 02:00",
              "temp_c": 14.6,
              "temp_f": 58.3,
              "is_day": 0,
              "condition": {
                "text": "Light rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
                "code": 1183
              },
              "wind_mph": 11.9,
              "wind_kph": 19.1,
              "wind_degree": 67,
              "wind_dir": "ENE",
              "pressure_mb": 979,
              "pressure_in": 28.91,
              "precip_mm": 1.06,
              "precip_in": 0.04,
              "humidity": 91,
              "cloud": 100,
              "feelslike_c": 13.2,
              "feelslike_f": 55.8,
              "windchill_c": 13.2,
              "windchill_f": 55.8,
              "heatindex_c": 14.6,
              "heatindex_f": 58.2,
              "dewpoint_c": 13.2,
              "dewpoint_f": 55.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 17.4,
              "gust_kph": 28,
              "uv": 1
            },
            {
              "time_epoch": 1697767200,
              "time": "2023-10-20 03:00",
              "temp_c": 14.6,
              "temp_f": 58.2,
              "is_day": 0,
              "condition": {
                "text": "Light rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
                "code": 1183
              },
              "wind_mph": 14.1,
              "wind_kph": 22.7,
              "wind_degree": 83,
              "wind_dir": "E",
              "pressure_mb": 978,
              "pressure_in": 28.88,
              "precip_mm": 1.86,
              "precip_in": 0.07,
              "humidity": 94,
              "cloud": 100,
              "feelslike_c": 12.9,
              "feelslike_f": 55.3,
              "windchill_c": 12.9,
              "windchill_f": 55.3,
              "heatindex_c": 14.6,
              "heatindex_f": 58.2,
              "dewpoint_c": 13.5,
              "dewpoint_f": 56.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 20.3,
              "gust_kph": 32.7,
              "uv": 1
            },
            {
              "time_epoch": 1697770800,
              "time": "2023-10-20 04:00",
              "temp_c": 14.7,
              "temp_f": 58.5,
              "is_day": 0,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                "code": 1240
              },
              "wind_mph": 13,
              "wind_kph": 20.9,
              "wind_degree": 81,
              "wind_dir": "E",
              "pressure_mb": 977,
              "pressure_in": 28.86,
              "precip_mm": 0.3,
              "precip_in": 0.01,
              "humidity": 93,
              "cloud": 100,
              "feelslike_c": 13.3,
              "feelslike_f": 56,
              "windchill_c": 13.3,
              "windchill_f": 56,
              "heatindex_c": 14.8,
              "heatindex_f": 58.6,
              "dewpoint_c": 13.6,
              "dewpoint_f": 56.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 18.8,
              "gust_kph": 30.2,
              "uv": 1
            },
            {
              "time_epoch": 1697774400,
              "time": "2023-10-20 05:00",
              "temp_c": 14.7,
              "temp_f": 58.5,
              "is_day": 0,
              "condition": {
                "text": "Moderate rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/302.png",
                "code": 1189
              },
              "wind_mph": 14.5,
              "wind_kph": 23.4,
              "wind_degree": 83,
              "wind_dir": "E",
              "pressure_mb": 977,
              "pressure_in": 28.85,
              "precip_mm": 3.18,
              "precip_in": 0.13,
              "humidity": 94,
              "cloud": 100,
              "feelslike_c": 13.1,
              "feelslike_f": 55.6,
              "windchill_c": 13.1,
              "windchill_f": 55.6,
              "heatindex_c": 14.7,
              "heatindex_f": 58.5,
              "dewpoint_c": 13.7,
              "dewpoint_f": 56.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 7,
              "vis_miles": 4,
              "gust_mph": 20.9,
              "gust_kph": 33.6,
              "uv": 1
            },
            {
              "time_epoch": 1697778000,
              "time": "2023-10-20 06:00",
              "temp_c": 14.6,
              "temp_f": 58.3,
              "is_day": 0,
              "condition": {
                "text": "Moderate rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/302.png",
                "code": 1189
              },
              "wind_mph": 14.3,
              "wind_kph": 23,
              "wind_degree": 77,
              "wind_dir": "ENE",
              "pressure_mb": 976,
              "pressure_in": 28.81,
              "precip_mm": 4.82,
              "precip_in": 0.19,
              "humidity": 95,
              "cloud": 100,
              "feelslike_c": 13,
              "feelslike_f": 55.4,
              "windchill_c": 13,
              "windchill_f": 55.4,
              "heatindex_c": 14.6,
              "heatindex_f": 58.3,
              "dewpoint_c": 13.8,
              "dewpoint_f": 56.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 7,
              "vis_miles": 4,
              "gust_mph": 20.7,
              "gust_kph": 33.4,
              "uv": 1
            },
            {
              "time_epoch": 1697781600,
              "time": "2023-10-20 07:00",
              "temp_c": 14.6,
              "temp_f": 58.3,
              "is_day": 0,
              "condition": {
                "text": "Moderate rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/302.png",
                "code": 1189
              },
              "wind_mph": 14.8,
              "wind_kph": 23.8,
              "wind_degree": 69,
              "wind_dir": "ENE",
              "pressure_mb": 975,
              "pressure_in": 28.8,
              "precip_mm": 4.64,
              "precip_in": 0.18,
              "humidity": 95,
              "cloud": 100,
              "feelslike_c": 12.9,
              "feelslike_f": 55.2,
              "windchill_c": 12.9,
              "windchill_f": 55.2,
              "heatindex_c": 14.6,
              "heatindex_f": 58.3,
              "dewpoint_c": 13.8,
              "dewpoint_f": 56.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 7,
              "vis_miles": 4,
              "gust_mph": 21.3,
              "gust_kph": 34.3,
              "uv": 1
            },
            {
              "time_epoch": 1697785200,
              "time": "2023-10-20 08:00",
              "temp_c": 14.4,
              "temp_f": 58,
              "is_day": 1,
              "condition": {
                "text": "Light rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                "code": 1183
              },
              "wind_mph": 15.7,
              "wind_kph": 25.2,
              "wind_degree": 65,
              "wind_dir": "ENE",
              "pressure_mb": 974,
              "pressure_in": 28.77,
              "precip_mm": 2.33,
              "precip_in": 0.09,
              "humidity": 94,
              "cloud": 100,
              "feelslike_c": 12.6,
              "feelslike_f": 54.7,
              "windchill_c": 12.6,
              "windchill_f": 54.7,
              "heatindex_c": 14.4,
              "heatindex_f": 58,
              "dewpoint_c": 13.6,
              "dewpoint_f": 56.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 22.5,
              "gust_kph": 36.2,
              "uv": 3
            },
            {
              "time_epoch": 1697788800,
              "time": "2023-10-20 09:00",
              "temp_c": 14.5,
              "temp_f": 58.1,
              "is_day": 1,
              "condition": {
                "text": "Light rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                "code": 1183
              },
              "wind_mph": 15.4,
              "wind_kph": 24.8,
              "wind_degree": 72,
              "wind_dir": "ENE",
              "pressure_mb": 973,
              "pressure_in": 28.74,
              "precip_mm": 1.69,
              "precip_in": 0.07,
              "humidity": 94,
              "cloud": 100,
              "feelslike_c": 12.7,
              "feelslike_f": 54.9,
              "windchill_c": 12.7,
              "windchill_f": 54.9,
              "heatindex_c": 14.5,
              "heatindex_f": 58.1,
              "dewpoint_c": 13.6,
              "dewpoint_f": 56.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 22.1,
              "gust_kph": 35.5,
              "uv": 3
            },
            {
              "time_epoch": 1697792400,
              "time": "2023-10-20 10:00",
              "temp_c": 14.4,
              "temp_f": 58,
              "is_day": 1,
              "condition": {
                "text": "Moderate rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
                "code": 1189
              },
              "wind_mph": 15.9,
              "wind_kph": 25.6,
              "wind_degree": 72,
              "wind_dir": "ENE",
              "pressure_mb": 972,
              "pressure_in": 28.71,
              "precip_mm": 6.02,
              "precip_in": 0.24,
              "humidity": 95,
              "cloud": 100,
              "feelslike_c": 12.6,
              "feelslike_f": 54.7,
              "windchill_c": 12.6,
              "windchill_f": 54.7,
              "heatindex_c": 14.4,
              "heatindex_f": 58,
              "dewpoint_c": 13.7,
              "dewpoint_f": 56.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 7,
              "vis_miles": 4,
              "gust_mph": 23,
              "gust_kph": 37,
              "uv": 3
            },
            {
              "time_epoch": 1697796000,
              "time": "2023-10-20 11:00",
              "temp_c": 14.4,
              "temp_f": 57.9,
              "is_day": 1,
              "condition": {
                "text": "Light rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                "code": 1183
              },
              "wind_mph": 11.9,
              "wind_kph": 19.1,
              "wind_degree": 80,
              "wind_dir": "E",
              "pressure_mb": 971,
              "pressure_in": 28.69,
              "precip_mm": 2.3,
              "precip_in": 0.09,
              "humidity": 96,
              "cloud": 100,
              "feelslike_c": 13,
              "feelslike_f": 55.4,
              "windchill_c": 13,
              "windchill_f": 55.4,
              "heatindex_c": 14.4,
              "heatindex_f": 57.9,
              "dewpoint_c": 13.8,
              "dewpoint_f": 56.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 17.2,
              "gust_kph": 27.7,
              "uv": 3
            },
            {
              "time_epoch": 1697799600,
              "time": "2023-10-20 12:00",
              "temp_c": 14.5,
              "temp_f": 58.1,
              "is_day": 1,
              "condition": {
                "text": "Light rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                "code": 1183
              },
              "wind_mph": 5.4,
              "wind_kph": 8.6,
              "wind_degree": 162,
              "wind_dir": "SSE",
              "pressure_mb": 971,
              "pressure_in": 28.68,
              "precip_mm": 1.32,
              "precip_in": 0.05,
              "humidity": 93,
              "cloud": 100,
              "feelslike_c": 14.2,
              "feelslike_f": 57.6,
              "windchill_c": 14.2,
              "windchill_f": 57.6,
              "heatindex_c": 14.5,
              "heatindex_f": 58.1,
              "dewpoint_c": 13.4,
              "dewpoint_f": 56.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 7.6,
              "gust_kph": 12.3,
              "uv": 3
            },
            {
              "time_epoch": 1697803200,
              "time": "2023-10-20 13:00",
              "temp_c": 14.5,
              "temp_f": 58,
              "is_day": 1,
              "condition": {
                "text": "Light drizzle",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
                "code": 1153
              },
              "wind_mph": 11.9,
              "wind_kph": 19.1,
              "wind_degree": 198,
              "wind_dir": "SSW",
              "pressure_mb": 971,
              "pressure_in": 28.67,
              "precip_mm": 0.3,
              "precip_in": 0.01,
              "humidity": 90,
              "cloud": 100,
              "feelslike_c": 13.1,
              "feelslike_f": 55.5,
              "windchill_c": 13.1,
              "windchill_f": 55.5,
              "heatindex_c": 14.5,
              "heatindex_f": 58,
              "dewpoint_c": 12.9,
              "dewpoint_f": 55.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 15.6,
              "gust_kph": 25.1,
              "uv": 3
            },
            {
              "time_epoch": 1697806800,
              "time": "2023-10-20 14:00",
              "temp_c": 13.7,
              "temp_f": 56.6,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 15,
              "wind_kph": 24.1,
              "wind_degree": 200,
              "wind_dir": "SSW",
              "pressure_mb": 972,
              "pressure_in": 28.69,
              "precip_mm": 0.32,
              "precip_in": 0.01,
              "humidity": 89,
              "cloud": 100,
              "feelslike_c": 11.7,
              "feelslike_f": 53,
              "windchill_c": 11.7,
              "windchill_f": 53,
              "heatindex_c": 13.7,
              "heatindex_f": 56.6,
              "dewpoint_c": 11.9,
              "dewpoint_f": 53.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 20.7,
              "gust_kph": 33.3,
              "uv": 3
            },
            {
              "time_epoch": 1697810400,
              "time": "2023-10-20 15:00",
              "temp_c": 14,
              "temp_f": 57.2,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 16.6,
              "wind_kph": 26.6,
              "wind_degree": 191,
              "wind_dir": "SSW",
              "pressure_mb": 972,
              "pressure_in": 28.7,
              "precip_mm": 0.26,
              "precip_in": 0.01,
              "humidity": 83,
              "cloud": 100,
              "feelslike_c": 12,
              "feelslike_f": 53.6,
              "windchill_c": 12,
              "windchill_f": 53.6,
              "heatindex_c": 14,
              "heatindex_f": 57.3,
              "dewpoint_c": 11.3,
              "dewpoint_f": 52.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 23.6,
              "gust_kph": 38,
              "uv": 3
            },
            {
              "time_epoch": 1697814000,
              "time": "2023-10-20 16:00",
              "temp_c": 14.2,
              "temp_f": 57.5,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 15.9,
              "wind_kph": 25.6,
              "wind_degree": 186,
              "wind_dir": "S",
              "pressure_mb": 971,
              "pressure_in": 28.69,
              "precip_mm": 0.04,
              "precip_in": 0,
              "humidity": 81,
              "cloud": 70,
              "feelslike_c": 12.2,
              "feelslike_f": 54,
              "windchill_c": 12.2,
              "windchill_f": 54,
              "heatindex_c": 14.2,
              "heatindex_f": 57.5,
              "dewpoint_c": 11,
              "dewpoint_f": 51.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 23.3,
              "gust_kph": 37.5,
              "uv": 3
            },
            {
              "time_epoch": 1697817600,
              "time": "2023-10-20 17:00",
              "temp_c": 13.9,
              "temp_f": 57.1,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 17,
              "wind_kph": 27.4,
              "wind_degree": 170,
              "wind_dir": "S",
              "pressure_mb": 971,
              "pressure_in": 28.69,
              "precip_mm": 0.03,
              "precip_in": 0,
              "humidity": 82,
              "cloud": 88,
              "feelslike_c": 11.8,
              "feelslike_f": 53.3,
              "windchill_c": 11.8,
              "windchill_f": 53.3,
              "heatindex_c": 13.9,
              "heatindex_f": 57.1,
              "dewpoint_c": 10.8,
              "dewpoint_f": 51.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 25,
              "gust_kph": 40.2,
              "uv": 3
            },
            {
              "time_epoch": 1697821200,
              "time": "2023-10-20 18:00",
              "temp_c": 13.7,
              "temp_f": 56.7,
              "is_day": 0,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                "code": 1063
              },
              "wind_mph": 19,
              "wind_kph": 30.6,
              "wind_degree": 171,
              "wind_dir": "S",
              "pressure_mb": 972,
              "pressure_in": 28.69,
              "precip_mm": 0.1,
              "precip_in": 0,
              "humidity": 84,
              "cloud": 100,
              "feelslike_c": 11.4,
              "feelslike_f": 52.5,
              "windchill_c": 11.4,
              "windchill_f": 52.5,
              "heatindex_c": 13.7,
              "heatindex_f": 56.7,
              "dewpoint_c": 11,
              "dewpoint_f": 51.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 27.4,
              "gust_kph": 44.2,
              "uv": 1
            },
            {
              "time_epoch": 1697824800,
              "time": "2023-10-20 19:00",
              "temp_c": 13.5,
              "temp_f": 56.3,
              "is_day": 0,
              "condition": {
                "text": "Light drizzle",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                "code": 1153
              },
              "wind_mph": 18.8,
              "wind_kph": 30.2,
              "wind_degree": 164,
              "wind_dir": "SSE",
              "pressure_mb": 971,
              "pressure_in": 28.69,
              "precip_mm": 0.2,
              "precip_in": 0.01,
              "humidity": 82,
              "cloud": 100,
              "feelslike_c": 11.2,
              "feelslike_f": 52.1,
              "windchill_c": 11.2,
              "windchill_f": 52.1,
              "heatindex_c": 13.5,
              "heatindex_f": 56.3,
              "dewpoint_c": 10.5,
              "dewpoint_f": 50.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 26.6,
              "gust_kph": 42.7,
              "uv": 1
            },
            {
              "time_epoch": 1697828400,
              "time": "2023-10-20 20:00",
              "temp_c": 13.1,
              "temp_f": 55.6,
              "is_day": 0,
              "condition": {
                "text": "Light drizzle",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                "code": 1153
              },
              "wind_mph": 15.4,
              "wind_kph": 24.8,
              "wind_degree": 183,
              "wind_dir": "S",
              "pressure_mb": 972,
              "pressure_in": 28.69,
              "precip_mm": 0.71,
              "precip_in": 0.03,
              "humidity": 89,
              "cloud": 100,
              "feelslike_c": 11,
              "feelslike_f": 51.7,
              "windchill_c": 11,
              "windchill_f": 51.7,
              "heatindex_c": 13.1,
              "heatindex_f": 55.6,
              "dewpoint_c": 11.4,
              "dewpoint_f": 52.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 20.8,
              "gust_kph": 33.6,
              "uv": 1
            },
            {
              "time_epoch": 1697832000,
              "time": "2023-10-20 21:00",
              "temp_c": 12.6,
              "temp_f": 54.8,
              "is_day": 0,
              "condition": {
                "text": "Light rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
                "code": 1183
              },
              "wind_mph": 12.8,
              "wind_kph": 20.5,
              "wind_degree": 173,
              "wind_dir": "S",
              "pressure_mb": 972,
              "pressure_in": 28.7,
              "precip_mm": 1.62,
              "precip_in": 0.06,
              "humidity": 91,
              "cloud": 100,
              "feelslike_c": 10.7,
              "feelslike_f": 51.2,
              "windchill_c": 10.7,
              "windchill_f": 51.2,
              "heatindex_c": 12.6,
              "heatindex_f": 54.8,
              "dewpoint_c": 11.2,
              "dewpoint_f": 52.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 17.7,
              "gust_kph": 28.5,
              "uv": 1
            },
            {
              "time_epoch": 1697835600,
              "time": "2023-10-20 22:00",
              "temp_c": 12.2,
              "temp_f": 53.9,
              "is_day": 0,
              "condition": {
                "text": "Light rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
                "code": 1183
              },
              "wind_mph": 10.5,
              "wind_kph": 16.9,
              "wind_degree": 183,
              "wind_dir": "S",
              "pressure_mb": 972,
              "pressure_in": 28.71,
              "precip_mm": 0.93,
              "precip_in": 0.04,
              "humidity": 89,
              "cloud": 91,
              "feelslike_c": 10.4,
              "feelslike_f": 50.7,
              "windchill_c": 10.4,
              "windchill_f": 50.7,
              "heatindex_c": 12.2,
              "heatindex_f": 53.9,
              "dewpoint_c": 10.5,
              "dewpoint_f": 50.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 14.2,
              "gust_kph": 22.9,
              "uv": 1
            },
            {
              "time_epoch": 1697839200,
              "time": "2023-10-20 23:00",
              "temp_c": 11.6,
              "temp_f": 52.9,
              "is_day": 0,
              "condition": {
                "text": "Light rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
                "code": 1183
              },
              "wind_mph": 11,
              "wind_kph": 17.6,
              "wind_degree": 188,
              "wind_dir": "S",
              "pressure_mb": 973,
              "pressure_in": 28.73,
              "precip_mm": 2.16,
              "precip_in": 0.09,
              "humidity": 91,
              "cloud": 100,
              "feelslike_c": 9.6,
              "feelslike_f": 49.3,
              "windchill_c": 9.6,
              "windchill_f": 49.3,
              "heatindex_c": 11.6,
              "heatindex_f": 52.9,
              "dewpoint_c": 10.2,
              "dewpoint_f": 50.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 14.6,
              "gust_kph": 23.5,
              "uv": 1
            }
          ]
        }
      ]
    }
  }

  export default hourData